<?xml version="1.0" standalone="no"?>
<!DOCTYPE products [
<!ENTITY miu "Made in USA">

<!ELEMENT products (prod+)>
<!ELEMENT prod (details+, quantity, unit_price, loc, color*)>
<!ATTLIST prod ProdID ID #REQUIRED>

<!ELEMENT details (short_desc, long_desc)>
<!ELEMENT short_desc (#PCDATA)>
<!ELEMENT long_desc (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit_price (#PCDATA)>
<!ELEMENT loc (#PCDATA)>
<!ELEMENT color (#PCDATA)>
]>

<products>

<prod ProdID="P00129934">
<details>
  <short_desc>Website Magazine</short_desc>
  <long_desc>Printed issue Website Magazine</long_desc>
</details>
<quantity>20</quantity>
<unit_price>3.50</unit_price>
<loc>&miu;</loc>
</prod>

<prod ProdID="P1234567">
<details>
  <short_desc>Lab Apron</short_desc>
  <long_desc>Chemistry Lab Apron</long_desc>
</details>
<quantity>30</quantity>
<unit_price>5.50</unit_price>
<color>White</color>
<loc>&miu;</loc>
</prod>

<prod ProdID="P3256788">
<details>
  <short_desc>T-Shirt</short_desc>
  <long_desc>College cotton shirt</long_desc>
</details>
<quantity>28</quantity>
<unit_price>6.50</unit_price>
<color>Red</color>
<loc>&miu;</loc>
</prod>

<prod ProdID="P0025443">
<details>
  <short_desc>Notebook</short_desc>
  <long_desc>5-Subject Notebook</long_desc>
</details>
<quantity>15</quantity>
<unit_price>2.65</unit_price>
<loc>&miu;</loc>
</prod>

</products>